apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering-deployment
  namespace: 2401086
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-ordering
  template:
    metadata:
      labels:
        app: food-ordering
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: food-ordering
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/my-repository/2401086_food_ordering/food-ordering:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80